public enum MessageID
{
    ADD_INVENTORY = 52,
    ADD_EXP_SP = 95,
    ENCHANT_FAIL = 65,
    USE_SKILL = 936,
    NOT_HAVE_ADENA = 279,
    NOT_ENOUGH_SP_TO_LEARN_SKILL = 278,
    NO_ITEM_DEPOSITED_IN_WH = 282,
    LEARNED_SKILL_S1 = 277,
    ITEM_MISSING_TO_LEARN_SKILL = 276
}
